MSCDLL_PATH = '../bin/msc.dll'
SAMPLE_RATE_16K = 16000
MAX_GRAMMARID_LEN = 32

ASR_RES_PATH = 'fo|res/asr/common.jet'
GRM_BUILD_PATH = 'res/asr/GrmBuilld'
GRM_FILE = '../bin/monitor.bnf'

MSP_SUCCESS = 0
MSP_AUDIO_SAMPLE_CONTINUE = 2
MSP_EP_LOOKING_FOR_SPEECH = 0
MSP_AUDIO_SAMPLE_FIRST = 1
MSP_REC_STATUS_INCOMPLETE = 2
MSP_EP_AFTER_SPEECH = 3
MSP_REC_STATUS_COMPLETE = 5
MSP_AUDIO_SAMPLE_LAST = 4

LOGIN_CONFIG = b'appid = 5cc8309a'
